# Generated by Django 6.0 on 2026-01-13 00:57

from django.db import migrations
from django.db.migrations import RunPython
from sequences.models import Sequence


def update_sequences_for_model_renames(apps, schema_editor):
    Sequence.objects.filter(name="edc_pharmacy.confirmationatsiteitem").update(
        name="edc_pharmacy.confirmationatlocationitem"
    )
    Sequence.objects.filter(name="edc_pharmacy.confirmationatsite").update(
        name="edc_pharmacy.confirmationatlocation"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("edc_pharmacy", "0093_alter_confirmationatlocation_options_and_more"),
    ]

    operations = [RunPython(update_sequences_for_model_renames)]
