# Generated by Django 6.0 on 2026-01-13 17:05

from django.db import migrations
from django.db.migrations import RunPython
from tqdm import tqdm

from edc_pharmacy.models import ConfirmationAtLocationItem, Stock


def update_stock_code(apps, schema_editor):
    qs = ConfirmationAtLocationItem.objects.filter(stock_transfer_item__isnull=True)
    for obj in tqdm(qs, total=qs.count()):
        stock_obj = Stock.objects.get(code=obj.stock.code)
        if stock_obj.stocktransferitem_set.all().count() == 1:
            obj.stock_transfer_item = stock_obj.stocktransferitem_set.all()[0]
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("edc_pharmacy", "0094_auto_20260113_0357"),
    ]

    operations = [RunPython(update_stock_code)]
