# Generated by Django 6.0 on 2026-01-14 15:00

from django.db import migrations
from django.db.migrations import RunPython
from tqdm import tqdm

from edc_pharmacy.models import ConfirmationAtLocationItem, Stock


def update_confirmation_at_location_item(apps, schema_editor):
    qs = ConfirmationAtLocationItem.objects.all()
    for obj in tqdm(qs, total=qs.count()):
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("edc_pharmacy", "0095_auto_20260113_2005"),
    ]

    operations = [RunPython(update_confirmation_at_location_item)]
