# Generated by Django 6.0 on 2026-01-18 17:12

from django.db import migrations
from edc_pharmacy.models import ConfirmationAtLocationItem, DispenseItem, StockTransferItem, \
    StorageBinItem

from tqdm import tqdm


def update_stock_boolean_fields(apps, schema_editor):

    print("\nUpdating boolean fields on the Stock model ...")
    print("  iterating over 1 / 4 models (StockTransferItem)...")
    qs = StockTransferItem.objects.all()
    for obj in tqdm(qs, total=qs.count()):
        obj.save()

    print("  iterating over 2 / 4 models (ConfirmationAtLocationItem)...")
    qs = ConfirmationAtLocationItem.objects.all()
    for obj in tqdm(qs, total=qs.count()):
        obj.save()

    print("  iterating over 3 / 4 models (StorageBinItem)...")
    qs = StorageBinItem.objects.all()
    for obj in tqdm(qs, total=qs.count()):
        obj.save()

    print("  iterating over 4 / 4 models (DispenseItem)...")
    qs = DispenseItem.objects.all()
    for obj in tqdm(qs, total=qs.count()):
        obj.save()
    print("Done.")


class Migration(migrations.Migration):
    dependencies = [
        ("edc_pharmacy", "0099_historicalstock_confirmed_at_location_and_more"),
    ]

    operations = [migrations.RunPython(update_stock_boolean_fields)]
