# Generated by Django 5.2.10 on 2026-03-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0136_stockavailability_visit_code_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockavailability",
            name="label",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
