# Generated by Django 6.0.4 on 2026-04-25 15:01

import _socket
import django.db.models.deletion
import django.utils.timezone
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_revision.revision_field
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0138_alter_containertype_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalStockTransaction",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                        max_length=75,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        default="",
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device created",
                    ),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device modified",
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                (
                    "transaction_datetime",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received (label confirmed)"),
                            ("REPACK_CONSUMED", "Repack — bulk consumed"),
                            ("REPACK_PRODUCED", "Repack — patient bottle produced"),
                            ("ALLOCATED", "Allocated to subject"),
                            ("ALLOCATION_ENDED", "Allocation ended"),
                            ("TRANSFER_DISPATCHED", "Transfer dispatched"),
                            ("TRANSFER_RECEIVED", "Transfer received at location"),
                            ("STORED", "Stored in bin"),
                            ("BIN_MOVED", "Moved to different bin"),
                            ("DISPENSED", "Dispensed to patient"),
                            ("RETURN_REQUESTED", "Return requested"),
                            ("RETURN_DISPATCHED", "Return dispatched to central"),
                            ("RETURN_RECEIVED", "Return received at central"),
                            (
                                "RETURN_DISPOSITION_REPOOLED",
                                "Return disposition — re-pooled",
                            ),
                            (
                                "RETURN_DISPOSITION_QUARANTINED",
                                "Return disposition — quarantined",
                            ),
                            (
                                "RETURN_DISPOSITION_DESTROYED",
                                "Return disposition — destroyed",
                            ),
                            ("ADJUSTED", "Quantity adjusted"),
                            ("DAMAGED", "Damaged"),
                            ("LOST", "Lost"),
                            ("EXPIRED", "Expired"),
                            ("VOIDED", "Voided"),
                            ("REVERSAL", "Reversal"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                (
                    "qty_delta",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "unit_qty_delta",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("state_after", models.JSONField(default=dict)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Stock transaction",
                "verbose_name_plural": "historical Stock transactions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveIndex(
            model_name="stocktransactiontype",
            name="edc_pharmac_display_46f88a_idx",
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "Received (label confirmed)"),
                    ("REPACK_CONSUMED", "Repack — bulk consumed"),
                    ("REPACK_PRODUCED", "Repack — patient bottle produced"),
                    ("ALLOCATED", "Allocated to subject"),
                    ("ALLOCATION_ENDED", "Allocation ended"),
                    ("TRANSFER_DISPATCHED", "Transfer dispatched"),
                    ("TRANSFER_RECEIVED", "Transfer received at location"),
                    ("STORED", "Stored in bin"),
                    ("BIN_MOVED", "Moved to different bin"),
                    ("DISPENSED", "Dispensed to patient"),
                    ("RETURN_REQUESTED", "Return requested"),
                    ("RETURN_DISPATCHED", "Return dispatched to central"),
                    ("RETURN_RECEIVED", "Return received at central"),
                    ("RETURN_DISPOSITION_REPOOLED", "Return disposition — re-pooled"),
                    (
                        "RETURN_DISPOSITION_QUARANTINED",
                        "Return disposition — quarantined",
                    ),
                    ("RETURN_DISPOSITION_DESTROYED", "Return disposition — destroyed"),
                    ("ADJUSTED", "Quantity adjusted"),
                    ("DAMAGED", "Damaged"),
                    ("LOST", "Lost"),
                    ("EXPIRED", "Expired"),
                    ("VOIDED", "Voided"),
                    ("REVERSAL", "Reversal"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.RemoveIndex(
            model_name="stocktransaction",
            name="edc_pharmac_modifie_69d29d_idx",
        ),
        migrations.RemoveIndex(
            model_name="stocktransaction",
            name="edc_pharmac_user_mo_01143b_idx",
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="damaged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="expired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="lost",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="quarantined",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="return_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="voided",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stock",
            name="damaged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stock",
            name="expired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stock",
            name="lost",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stock",
            name="quarantined",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stock",
            name="return_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stock",
            name="voided",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="dispense_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="edc_pharmacy.dispenseitem",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="from_allocation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="edc_pharmacy.allocation",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="from_bin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="edc_pharmacy.storagebin",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="from_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="edc_pharmacy.location",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="qty_delta",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="reason",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="receive_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="edc_pharmacy.receiveitem",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="repack_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="edc_pharmacy.repackrequest",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="reverses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversed_by",
                to="edc_pharmacy.stocktransaction",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="state_after",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="stock_adjustment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="edc_pharmacy.stockadjustment",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="stock_transfer_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="edc_pharmacy.stocktransferitem",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="to_allocation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="edc_pharmacy.allocation",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="to_bin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="edc_pharmacy.storagebin",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="to_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="edc_pharmacy.location",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="unit_qty_delta",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="allocation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Subject allocation. TODO(allocation-refactor): replace with current_allocation FK.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.allocation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="confirmed_at_location",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="dispensed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="in_transit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="stored_at_location",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="stock",
            name="allocation",
            field=models.OneToOneField(
                blank=True,
                help_text="Subject allocation. TODO(allocation-refactor): replace with current_allocation FK.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="edc_pharmacy.allocation",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="confirmed_at_location",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="stock",
            name="dispensed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="stock",
            name="in_transit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stored_at_location",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="edc_pharmacy.stock",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_datetime",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["stock", "-transaction_datetime"],
                name="edc_pharmac_stock_i_2ad899_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["transaction_type", "-transaction_datetime"],
                name="edc_pharmac_transac_c03f70_idx",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktransaction",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktransaction",
            name="dispense_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.dispenseitem",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktransaction",
            name="from_allocation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.allocation",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktransaction",
            name="from_bin",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.storagebin",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktransaction",
            name="from_location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.location",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktransaction",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktransaction",
            name="receive_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.receiveitem",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktransaction",
            name="repack_request",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.repackrequest",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktransaction",
            name="reverses",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.stocktransaction",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktransaction",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.stock",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktransaction",
            name="stock_adjustment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.stockadjustment",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktransaction",
            name="stock_transfer_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.stocktransferitem",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktransaction",
            name="to_allocation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.allocation",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktransaction",
            name="to_bin",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.storagebin",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktransaction",
            name="to_location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.location",
            ),
        ),
        migrations.DeleteModel(
            name="StockTransactionType",
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="transaction_qty",
        ),
    ]
