# Generated by Django 6.0.4 on 2026-04-28 02:20

import _socket
import django.db.models.deletion
import django.db.models.manager
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_revision.revision_field
import edc_sites.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0146_stocktake_stocktakeitem"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalstocktake",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Stock take",
                "verbose_name_plural": "historical Stock takes",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstocktakeitem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Stock take item",
                "verbose_name_plural": "historical Stock take items",
            },
        ),
        migrations.AlterModelOptions(
            name="stocktake",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ["-stock_take_datetime"],
                "verbose_name": "Stock take",
                "verbose_name_plural": "Stock takes",
            },
        ),
        migrations.AlterModelOptions(
            name="stocktakeitem",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ["status", "code"],
                "verbose_name": "Stock take item",
                "verbose_name_plural": "Stock take items",
            },
        ),
        migrations.AlterModelManagers(
            name="stocktake",
            managers=[
                ("on_site", edc_sites.managers.CurrentSiteManager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name="allocation",
            name="edc_pharm_stock_started_idx",
        ),
        migrations.RemoveIndex(
            model_name="allocation",
            name="edc_pharm_alloc_ended_idx",
        ),
        migrations.RemoveField(
            model_name="historicalstocktake",
            name="locale",
        ),
        migrations.RemoveField(
            model_name="historicalstocktakeitem",
            name="locale",
        ),
        migrations.RemoveField(
            model_name="stocktake",
            name="locale",
        ),
        migrations.RemoveField(
            model_name="stocktakeitem",
            name="locale",
        ),
        migrations.AddField(
            model_name="historicalstocktake",
            name="locale_created",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktake",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktakeitem",
            name="locale_created",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="historicalstocktakeitem",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="locale_created",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="stocktake",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AddField(
            model_name="stocktakeitem",
            name="locale_created",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale created",
            ),
        ),
        migrations.AddField(
            model_name="stocktakeitem",
            name="locale_modified",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-updated by Modeladmin",
                max_length=10,
                verbose_name="Locale modified",
            ),
        ),
        migrations.AlterField(
            model_name="allocation",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                help_text="Stock item allocated to this subject.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="edc_pharmacy.stock",
            ),
        ),
        migrations.AlterField(
            model_name="historicalallocation",
            name="ended_datetime",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the allocation ended (NULL = still active).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalallocation",
            name="ended_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Why the allocation ended (dispensed, returned, reallocated, …).",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="historicalallocation",
            name="started_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="When the allocation became active (defaults to allocation_datetime).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalallocation",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Stock item allocated to this subject.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.stock",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="current_allocation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Active allocation for this stock item (NULL if unallocated or dispensed).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.allocation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="device_created",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device created"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="device_modified",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device modified"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="expected_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of items registered in the bin at the time of the stock take.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="history_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="hostname_created",
            field=models.CharField(
                blank=True,
                default=_socket.gethostname,
                help_text="System field. (modified on create only)",
                max_length=60,
                verbose_name="Hostname created",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="hostname_modified",
            field=django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                blank=True,
                default="",
                help_text="System field. (modified on every save)",
                max_length=50,
                verbose_name="Hostname modified",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="id",
            field=django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="System auto field. UUID primary key.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="revision",
            field=django_revision.revision_field.RevisionField(
                blank=True,
                default="",
                editable=False,
                help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                max_length=75,
                verbose_name="Revision",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="scanned_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of codes scanned during the stock take."
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="site",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="stock_take_identifier",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=36, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="user_created",
            field=django_audit_fields.fields.userfield.UserField(
                blank=True,
                default="",
                help_text="Updated by admin.save_model",
                max_length=50,
                verbose_name="user created",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="user_modified",
            field=django_audit_fields.fields.userfield.UserField(
                blank=True,
                default="",
                help_text="Updated by admin.save_model",
                max_length=50,
                verbose_name="user modified",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktakeitem",
            name="device_created",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device created"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktakeitem",
            name="device_modified",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device modified"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktakeitem",
            name="history_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktakeitem",
            name="hostname_created",
            field=models.CharField(
                blank=True,
                default=_socket.gethostname,
                help_text="System field. (modified on create only)",
                max_length=60,
                verbose_name="Hostname created",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktakeitem",
            name="hostname_modified",
            field=django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                blank=True,
                default="",
                help_text="System field. (modified on every save)",
                max_length=50,
                verbose_name="Hostname modified",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktakeitem",
            name="id",
            field=django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="System auto field. UUID primary key.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktakeitem",
            name="revision",
            field=django_revision.revision_field.RevisionField(
                blank=True,
                default="",
                editable=False,
                help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                max_length=75,
                verbose_name="Revision",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktakeitem",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Null if scanned code not found in the system.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.stock",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktakeitem",
            name="user_created",
            field=django_audit_fields.fields.userfield.UserField(
                blank=True,
                default="",
                help_text="Updated by admin.save_model",
                max_length=50,
                verbose_name="user created",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktakeitem",
            name="user_modified",
            field=django_audit_fields.fields.userfield.UserField(
                blank=True,
                default="",
                help_text="Updated by admin.save_model",
                max_length=50,
                verbose_name="user modified",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktransferitem",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={"current_allocation__isnull": False},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.stock",
            ),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="device_created",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device created"
            ),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="device_modified",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device modified"
            ),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="hostname_created",
            field=models.CharField(
                blank=True,
                default=_socket.gethostname,
                help_text="System field. (modified on create only)",
                max_length=60,
                verbose_name="Hostname created",
            ),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="hostname_modified",
            field=django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                blank=True,
                default="",
                help_text="System field. (modified on every save)",
                max_length=50,
                verbose_name="Hostname modified",
            ),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="id",
            field=django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                blank=True,
                editable=False,
                help_text="System auto field. UUID primary key.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="revision",
            field=django_revision.revision_field.RevisionField(
                blank=True,
                default="",
                editable=False,
                help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                max_length=75,
                verbose_name="Revision",
            ),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="sites.site",
            ),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="user_created",
            field=django_audit_fields.fields.userfield.UserField(
                blank=True,
                default="",
                help_text="Updated by admin.save_model",
                max_length=50,
                verbose_name="user created",
            ),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="user_modified",
            field=django_audit_fields.fields.userfield.UserField(
                blank=True,
                default="",
                help_text="Updated by admin.save_model",
                max_length=50,
                verbose_name="user modified",
            ),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="device_created",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device created"
            ),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="device_modified",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Device modified"
            ),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="hostname_created",
            field=models.CharField(
                blank=True,
                default=_socket.gethostname,
                help_text="System field. (modified on create only)",
                max_length=60,
                verbose_name="Hostname created",
            ),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="hostname_modified",
            field=django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                blank=True,
                default="",
                help_text="System field. (modified on every save)",
                max_length=50,
                verbose_name="Hostname modified",
            ),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="id",
            field=django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                blank=True,
                editable=False,
                help_text="System auto field. UUID primary key.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="revision",
            field=django_revision.revision_field.RevisionField(
                blank=True,
                default="",
                editable=False,
                help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                max_length=75,
                verbose_name="Revision",
            ),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                help_text="Null if scanned code not found in the system.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.stock",
            ),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="user_created",
            field=django_audit_fields.fields.userfield.UserField(
                blank=True,
                default="",
                help_text="Updated by admin.save_model",
                max_length=50,
                verbose_name="user created",
            ),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="user_modified",
            field=django_audit_fields.fields.userfield.UserField(
                blank=True,
                default="",
                help_text="Updated by admin.save_model",
                max_length=50,
                verbose_name="user modified",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransferitem",
            name="stock",
            field=models.ForeignKey(
                limit_choices_to={"current_allocation__isnull": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.stock",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktake",
            index=models.Index(
                fields=["modified", "created"], name="edc_pharmac_modifie_6baa9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktake",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_pharmac_user_mo_4d4906_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stocktakeitem",
            index=models.Index(
                fields=["modified", "created"], name="edc_pharmac_modifie_c1c4b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktakeitem",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_pharmac_user_mo_1a8338_idx",
            ),
        ),
    ]
