# Generated by Django 6.0.4 on 2026-04-28 19:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0148_auto_20260428_2221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorder",
            name="item_count",
            field=models.IntegerField(
                default=0,
                help_text="Cached count of order items. Updated automatically by signal.",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Item count",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorderitem",
            name="unit_qty_ordered",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                help_text="Updated automatically (containers * unit_quantity per container)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("1.0"))],
                verbose_name="Unit quantity ordered",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorderitem",
            name="unit_qty_pending",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                help_text="Unit quantity ordered - Unit quantity received. Updated automatically",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="Unit quantity pending",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorderitem",
            name="unit_qty_received",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                help_text="Updated automatically when units are received",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="Unit quantity received",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="expected_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of items registered in the bin at the time of the stock take.",
                verbose_name="Expected",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="matched_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Matched"),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="missing_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Missing"),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="scanned_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of codes scanned during the stock take.",
                verbose_name="Scanned",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktake",
            name="unexpected_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Unexpected"),
        ),
        migrations.AlterField(
            model_name="order",
            name="item_count",
            field=models.IntegerField(
                default=0,
                help_text="Cached count of order items. Updated automatically by signal.",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Item count",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_qty_ordered",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                help_text="Updated automatically (containers * unit_quantity per container)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("1.0"))],
                verbose_name="Unit quantity ordered",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_qty_pending",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                help_text="Unit quantity ordered - Unit quantity received. Updated automatically",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="Unit quantity pending",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_qty_received",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                help_text="Updated automatically when units are received",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
                verbose_name="Unit quantity received",
            ),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="expected_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of items registered in the bin at the time of the stock take.",
                verbose_name="Expected",
            ),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="matched_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Matched"),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="missing_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Missing"),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="scanned_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of codes scanned during the stock take.",
                verbose_name="Scanned",
            ),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="unexpected_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Unexpected"),
        ),
    ]
