# Generated by Django 6.0.4 on 2026-04-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0149_alter_historicalorder_item_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stocktake",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("-stock_take_datetime",),
                "verbose_name": "Stock take",
                "verbose_name_plural": "Stock takes",
            },
        ),
        migrations.AlterModelOptions(
            name="stocktakeitem",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("status", "code"),
                "verbose_name": "Stock take item",
                "verbose_name_plural": "Stock take items",
            },
        ),
        migrations.RenameField(
            model_name="historicalorder",
            old_name="sent",
            new_name="printed",
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="printed_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Username that triggered the first PDF print.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="printed_datetime",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of the first PDF print.", null=True
            ),
        ),
        migrations.RenameField(
            model_name="order",
            old_name="sent",
            new_name="printed",
        ),
        migrations.AddField(
            model_name="order",
            name="printed_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Username that triggered the first PDF print.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="printed_datetime",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of the first PDF print.", null=True
            ),
        ),
    ]
