# Generated by Django 6.0.4 on 2026-04-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "edc_pharmacy",
            "0150_alter_stocktake_options_alter_stocktakeitem_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorder",
            name="printed",
            field=models.BooleanField(
                default=False,
                help_text="Set automatically when the PDF is first printed.",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="printed",
            field=models.BooleanField(
                default=False,
                help_text="Set automatically when the PDF is first printed.",
            ),
        ),
    ]
