# Generated by Django 6.0.4 on 2026-05-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0151_alter_historicalorder_printed_alter_order_printed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockadjustment",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="stock_adjustment",
        ),
        migrations.RemoveField(
            model_name="historicalstocktransaction",
            name="stock_adjustment",
        ),
        migrations.AlterField(
            model_name="historicallot",
            name="lot_no",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="Lot # / Batch"
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="lot_no",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Lot # / Batch"
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalStockAdjustment",
        ),
        migrations.DeleteModel(
            name="StockAdjustment",
        ),
    ]
