# Generated by Django 6.0.4 on 2026-05-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0152_remove_stockadjustment_stock_and_more"),
        ("edc_visit_schedule", "0022_visitschedulesummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrequest",
            name="visit_schedules",
            field=models.ManyToManyField(
                blank=True,
                help_text="If left blank, all visit schedules will be included.",
                to="edc_visit_schedule.visitschedulesummary",
                verbose_name="Include these visit schedules only",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("PARTIAL", "Partial"),
                    ("COMPLETE", "Complete"),
                ],
                default="New",
                help_text="Updates in the signal",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("PARTIAL", "Partial"),
                    ("COMPLETE", "Complete"),
                ],
                default="New",
                help_text="Updates in the signal",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrx",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("PARTIAL", "Partially filled"),
                    ("filled", "Filled"),
                    ("cancelled", "Cancelled"),
                ],
                default="New",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("PARTIAL", "Partial"),
                    ("COMPLETE", "Complete"),
                ],
                default="New",
                help_text="Updates in the signal",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("PARTIAL", "Partial"),
                    ("COMPLETE", "Complete"),
                ],
                default="New",
                help_text="Updates in the signal",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="rx",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("PARTIAL", "Partially filled"),
                    ("filled", "Filled"),
                    ("cancelled", "Cancelled"),
                ],
                default="New",
                max_length=25,
            ),
        ),
    ]
