# Generated by Django 6.0.4 on 2026-05-04 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0153_stockrequest_visit_schedules_and_more"),
        (
            "edc_registration",
            "0034_alter_historicalregisteredsubject_revision_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalstock",
            old_name="current_allocation",
            new_name="allocation",
        ),
        migrations.RenameField(
            model_name="stock",
            old_name="current_allocation",
            new_name="allocation",
        ),

    ]
