# Generated by Django 6.0.4 on 2026-05-04 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0154_remove_historicalstock_current_allocation_and_more"),
        (
            "edc_registration",
            "0034_alter_historicalregisteredsubject_revision_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstock",
            name="allocation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Sticky pointer to the most recent Allocation for this stock item. Preserved across dispense, damage, destroy, expire, etc. for audit; cleared only when the stock is repooled (returned and made available again). To check whether the allocation is currently active, also test `allocation.ended_datetime IS NULL`.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.allocation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstocktransferitem",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={
                    "allocation__ended_datetime__isnull": True,
                    "allocation__isnull": False,
                },
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.stock",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="allocation",
            field=models.ForeignKey(
                blank=True,
                help_text="Sticky pointer to the most recent Allocation for this stock item. Preserved across dispense, damage, destroy, expire, etc. for audit; cleared only when the stock is repooled (returned and made available again). To check whether the allocation is currently active, also test `allocation.ended_datetime IS NULL`.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="edc_pharmacy.allocation",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransferitem",
            name="stock",
            field=models.ForeignKey(
                limit_choices_to={
                    "allocation__ended_datetime__isnull": True,
                    "allocation__isnull": False,
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.stock",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_datetime__isnull", True)),
                fields=("stock",),
                name="one_active_allocation_per_stock",
            ),
        ),
    ]
