# Generated by Django 6.0.4 on 2026-05-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0155_alter_historicalstock_allocation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("partial", "Partial"),
                    ("COMPLETE", "Complete"),
                ],
                default="New",
                help_text="Updates in the signal",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("partial", "Partial"),
                    ("COMPLETE", "Complete"),
                ],
                default="New",
                help_text="Updates in the signal",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrx",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("partial", "Partially filled"),
                    ("filled", "Filled"),
                    ("cancelled", "Cancelled"),
                ],
                default="New",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("partial", "Partial"),
                    ("COMPLETE", "Complete"),
                ],
                default="New",
                help_text="Updates in the signal",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("partial", "Partial"),
                    ("COMPLETE", "Complete"),
                ],
                default="New",
                help_text="Updates in the signal",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="rx",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("partial", "Partially filled"),
                    ("filled", "Filled"),
                    ("cancelled", "Cancelled"),
                ],
                default="New",
                max_length=25,
            ),
        ),
    ]
