# Generated by Django 6.0.6 on 2026-06-29 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0158_allocation_mysql_active_uniqueness"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstocktakeitem",
            name="stock_transaction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The ledger transaction that resolved this discrepancy, if any. Set when a correction (e.g. lost/damaged/expired or move-to-bin) is applied from the stock take. SET_NULL so the append-only ledger can be rebuilt without being blocked.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.stocktransaction",
            ),
        ),
        migrations.AddField(
            model_name="stocktakeitem",
            name="stock_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="The ledger transaction that resolved this discrepancy, if any. Set when a correction (e.g. lost/damaged/expired or move-to-bin) is applied from the stock take. SET_NULL so the append-only ledger can be rebuilt without being blocked.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="edc_pharmacy.stocktransaction",
            ),
        ),
    ]
