# Generated by Django 5.2.10 on 2026-04-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "edc_protocol_incident",
            "0026_alter_historicalprotocoldeviationviolation_revision_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actionsrequired",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("display_index", "display_name"),
                "verbose_name": "Actions Required",
                "verbose_name_plural": "Actions Required",
            },
        ),
        migrations.AlterModelOptions(
            name="protocolincidents",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("display_index", "display_name"),
                "verbose_name": "Protocol Incidents",
                "verbose_name_plural": "Protocol Incidents",
            },
        ),
        migrations.AlterModelOptions(
            name="protocolviolations",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("display_index", "display_name"),
                "verbose_name": "Protocol Violations",
                "verbose_name_plural": "Protocol Violations",
            },
        ),
    ]
