# Generated by Django 5.2.8 on 2025-11-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "edc_rx",
            "0004_remove_rxmodificationreasons_edc_rx_rxmo_name_b72a47_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rxmodificationreasons",
            name="extra_value",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="rxmodificationreasons",
            name="field_name",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Not required",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="rxmodificationreasons",
            name="plural_name",
            field=models.CharField(
                default="", max_length=250, verbose_name="Plural name"
            ),
        ),
        migrations.AlterField(
            model_name="rxmodifications",
            name="extra_value",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="rxmodifications",
            name="field_name",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Not required",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="rxmodifications",
            name="plural_name",
            field=models.CharField(
                default="", max_length=250, verbose_name="Plural name"
            ),
        ),
    ]
