from edc_sites.single_site import SingleSite
from edc_sites.site import sites

fqdn = "intecomm.clinicedc.org"

ug_language_codes = ["en", "lg", "ry", "sw"]
tz_language_codes = ["en", "sw", "mas"]


sites.register(
    SingleSite(
        101,
        "kasangati",
        country_code="ug",
        country="uganda",
        language_codes=ug_language_codes,
        domain=f"kasangati.ug.{fqdn}",
    ),
    SingleSite(
        102,
        "kisugu",
        country_code="ug",
        country="uganda",
        language_codes=ug_language_codes,
        domain=f"kisugu.ug.{fqdn}",
    ),
    SingleSite(
        103,
        "kiswa",
        country_code="ug",
        country="uganda",
        language_codes=ug_language_codes,
        domain=f"kiswa.ug.{fqdn}",
    ),
    SingleSite(
        104,
        "kyazanga",
        country_code="ug",
        country="uganda",
        language_codes=ug_language_codes,
        domain=f"kyazanga.ug.{fqdn}",
    ),
    SingleSite(
        105,
        "mpigi",
        country_code="ug",
        country="uganda",
        language_codes=ug_language_codes,
        domain=f"mpigi.ug.{fqdn}",
    ),
    SingleSite(
        106,
        "namayumba",
        country_code="ug",
        country="uganda",
        language_codes=ug_language_codes,
        domain=f"namayumba.ug.{fqdn}",
    ),
    SingleSite(
        107,
        "namulonge",
        country_code="ug",
        country="uganda",
        language_codes=ug_language_codes,
        domain=f"namulonge.ug.{fqdn}",
    ),
    SingleSite(
        108,
        "ndejje",
        country_code="ug",
        country="uganda",
        language_codes=ug_language_codes,
        domain=f"ndejje.ug.{fqdn}",
    ),
    SingleSite(
        109,
        "sekiwunga",
        country_code="ug",
        country="uganda",
        language_codes=ug_language_codes,
        domain=f"sekiwunga.ug.{fqdn}",
    ),
    SingleSite(
        110,
        "wakiso",
        country_code="ug",
        country="uganda",
        language_codes=ug_language_codes,
        domain=f"wakiso.ug.{fqdn}",
    ),
    SingleSite(
        201,
        "amana",
        title="Amana Hospital",
        country="tanzania",
        country_code="tz",
        language_codes=tz_language_codes,
        domain=f"amana.tz.{fqdn}",
    ),
    SingleSite(
        202,
        "bagamoyo",
        title="Bagamoyo Regional Hospital",
        country="tanzania",
        country_code="tz",
        language_codes=tz_language_codes,
        domain=f"bagamoyo.tz.{fqdn}",
    ),
    SingleSite(
        203,
        "rugambwa",
        title="Cardinal Rugambwa Hospital",
        country="tanzania",
        country_code="tz",
        language_codes=tz_language_codes,
        domain=f"rugambwa.tz.{fqdn}",
    ),
    SingleSite(
        204,
        "hindu_mandal",
        title="Hindu Mandal Hospital",
        country="tanzania",
        country_code="tz",
        language_codes=tz_language_codes,
        domain=f"hindu-mandal.tz.{fqdn}",
    ),
    SingleSite(
        205,
        "kisarawe",
        title="Kisarawe District Hospital",
        country="tanzania",
        country_code="tz",
        language_codes=tz_language_codes,
        domain=f"kisarawe.tz.{fqdn}",
    ),
    SingleSite(
        206,
        "mbagala",
        title="Mbagala Hospital",
        country="tanzania",
        country_code="tz",
        language_codes=tz_language_codes,
        domain=f"mbagala.tz.{fqdn}",
    ),
    SingleSite(
        207,
        "mnazi_moja",
        title="Mnazi Moja Hospital",
        country="tanzania",
        country_code="tz",
        language_codes=tz_language_codes,
        domain=f"mnazi.tz.{fqdn}",
    ),
    SingleSite(
        208,
        "mwananyamala",
        title="Mwananyamala Hospital",
        country="tanzania",
        country_code="tz",
        language_codes=tz_language_codes,
        domain=f"mwananyamala.tz.{fqdn}",
    ),
    SingleSite(
        209,
        "sinza",
        title="Sinza Hospital",
        country_code="tz",
        country="tanzania",
        language_codes=tz_language_codes,
        domain=f"sinza.tz.{fqdn}",
    ),
    SingleSite(
        210,
        "temeke",
        title="Temeke Hospital",
        country="tanzania",
        country_code="tz",
        language_codes=tz_language_codes,
        domain=f"temeke.tz.{fqdn}",
    ),
)
