# Generated by Django 6.0.8 on 2026-10-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_offstudy", "0025_alter_historicalsubjectoffstudy_revision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectoffstudy",
            name="offstudy_reason",
            field=models.CharField(
                choices=[
                    ("lost", "Lost to follow-up"),
                    ("completed protocol", "Completed protocol"),
                    ("consent_withdrawal", "Consent withdrawn"),
                    ("dead", "Deceased"),
                    ("OTHER", "Other, please specify ..."),
                ],
                max_length=125,
                verbose_name="Please code the primary reason participant taken off-study",
            ),
        ),
        migrations.AlterField(
            model_name="subjectoffstudy",
            name="offstudy_reason",
            field=models.CharField(
                choices=[
                    ("lost", "Lost to follow-up"),
                    ("completed protocol", "Completed protocol"),
                    ("consent_withdrawal", "Consent withdrawn"),
                    ("dead", "Deceased"),
                    ("OTHER", "Other, please specify ..."),
                ],
                max_length=125,
                verbose_name="Please code the primary reason participant taken off-study",
            ),
        ),
    ]
