# Generated by Django 5.2.10 on 2026-03-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_qareports", "0024_alter_historicalnote_status_alter_note_status"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="note",
            name="edc_qareports_note_report_model_subj_uniq",
        ),
        migrations.AddField(
            model_name="historicalnote",
            name="label",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="label",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.UniqueConstraint(
                fields=(
                    "report_model",
                    "subject_identifier",
                    "visit_code",
                    "visit_code_sequence",
                    "label",
                ),
                name="edc_qareports_note_report_model_subj_uniq",
            ),
        ),
    ]
