# Generated by Django 5.2.10 on 2026-04-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "edc_qareports",
            "0025_remove_note_edc_qareports_note_report_model_subj_uniq_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalnote",
            name="label",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="note",
            name="label",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
