# Generated by Django 5.2.10 on 2026-04-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edc_visit_tracking", "0011_alter_historicalsubjectvisit_revision_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectvisitmissedreasons",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("display_index", "display_name"),
                "verbose_name": "Subject Missed Visit Reasons",
                "verbose_name_plural": "Subject Missed Visit Reasons",
            },
        ),
        migrations.AlterModelOptions(
            name="visitreasons",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("display_index", "display_name"),
                "verbose_name": "Visit Reasons",
                "verbose_name_plural": "Visit Reasons",
            },
        ),
    ]
