# Generated by Django 6.0.4 on 2026-05-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_visit_tracking", "0012_alter_subjectvisitmissedreasons_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectvisit",
            name="document_status",
            field=models.CharField(
                choices=[
                    ("INCOMPLETE", "Incomplete (some data pending)"),
                    (
                        "crf_issue_detected",
                        "QA issue detected (see CRF status comment)",
                    ),
                    ("COMPLETE", "Complete"),
                ],
                default="COMPLETE",
                help_text="If some data is still pending, flag as incomplete",
                max_length=25,
                verbose_name="Document status",
            ),
        ),
        migrations.AlterField(
            model_name="subjectvisit",
            name="document_status",
            field=models.CharField(
                choices=[
                    ("INCOMPLETE", "Incomplete (some data pending)"),
                    (
                        "crf_issue_detected",
                        "QA issue detected (see CRF status comment)",
                    ),
                    ("COMPLETE", "Complete"),
                ],
                default="COMPLETE",
                help_text="If some data is still pending, flag as incomplete",
                max_length=25,
                verbose_name="Document status",
            ),
        ),
    ]
