# Generated by Django 5.2.10 on 2026-04-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_metadata", "0036_alter_requisitionmetadata_options_and_more"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="crfmetadata",
            index=models.Index(
                fields=[
                    "site",
                    "subject_identifier",
                    "visit_code",
                    "visit_code_sequence",
                    "show_order",
                ],
                name="edc_metadata_crfmetadata_a6idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crfmetadata",
            index=models.Index(
                fields=["visit_code"], name="edc_metadata_crfmetadata_a7idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crfmetadata",
            index=models.Index(
                fields=["schedule_name"], name="edc_metadata_crfmetadata_a8idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crfmetadata",
            index=models.Index(
                fields=["document_name"], name="edc_metadata_crfmetadata_a9idx"
            ),
        ),
    ]
