# Generated by Django 6.0.6 on 2026-06-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_metadata", "0037_crfmetadata_edc_metadata_crfmetadata_a6idx_and_more"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="crfmetadata",
            index=models.Index(
                fields=[
                    "entry_status",
                    "site",
                    "subject_identifier",
                    "visit_code",
                    "visit_code_sequence",
                    "show_order",
                ],
                name="edc_metadata_crf_a10idx",
            ),
        ),
        migrations.AddIndex(
            model_name="requisitionmetadata",
            index=models.Index(
                fields=[
                    "entry_status",
                    "site",
                    "subject_identifier",
                    "visit_code",
                    "visit_code_sequence",
                    "show_order",
                ],
                name="edc_metadata_req_a10idx",
            ),
        ),
    ]
