# Generated by Django 6.0.6 on 2026-06-23 00:07

import _socket
import django.utils.timezone
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_revision.revision_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_metadata", "0038_crfmetadata_edc_metadata_crfmetadata_a10idx_and_more"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrfPriority",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                        max_length=75,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        default="",
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device created",
                    ),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device modified",
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Dotted model label, e.g. 'my_app.myform'. Matches CrfMetadata.model.",
                        max_length=50,
                    ),
                ),
                ("visit_schedule_name", models.CharField(max_length=25)),
                ("schedule_name", models.CharField(max_length=25)),
                (
                    "metadata_kind",
                    models.CharField(
                        choices=[("crf", "CRF"), ("requisition", "Requisition")],
                        default="crf",
                        max_length=25,
                    ),
                ),
                (
                    "tier",
                    models.IntegerField(
                        choices=[(1, "Tier 1 (highest)"), (2, "Tier 2"), (3, "Tier 3")],
                        default=2,
                        help_text="Lower is higher priority. Tier 1 is highlighted on the review screen.",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "CRF priority",
                "verbose_name_plural": "CRF priorities",
                "ordering": ("tier", "schedule_name", "model"),
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "default_manager_name": "objects",
            },
        ),
        migrations.AddIndex(
            model_name="crfmetadata",
            index=models.Index(
                fields=[
                    "entry_status",
                    "site",
                    "schedule_name",
                    "model",
                    "visit_code",
                    "subject_identifier",
                ],
                name="edc_metadata_crf_a11idx",
            ),
        ),
        migrations.AddIndex(
            model_name="requisitionmetadata",
            index=models.Index(
                fields=[
                    "entry_status",
                    "site",
                    "schedule_name",
                    "model",
                    "visit_code",
                    "subject_identifier",
                ],
                name="edc_metadata_req_a11idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crfpriority",
            index=models.Index(
                fields=["modified", "created"], name="edc_metadat_modifie_b47490_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crfpriority",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_metadat_user_mo_4d959a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crfpriority",
            index=models.Index(
                fields=["active", "schedule_name", "tier"],
                name="edc_metadata_crfpriority_a0idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="crfpriority",
            constraint=models.UniqueConstraint(
                fields=(
                    "model",
                    "visit_schedule_name",
                    "schedule_name",
                    "metadata_kind",
                ),
                name="edc_metadata_crfpriority_model_schedule_uniq",
            ),
        ),
    ]
