# Generated by Django 6.0.6 on 2026-06-24 14:03

import _socket
import django.db.models.deletion
import django.utils.timezone
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_revision.revision_field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_metadata", "0040_dataunavailablereason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewFilter",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="System field. From git repository (tag:branch:commit), project metadata, project toml, project VERSION, or settings.",
                        max_length=75,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        default="",
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        default="",
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device created",
                    ),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Device modified",
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "query",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="urlencoded review board filter querystring",
                    ),
                ),
                ("shared", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Review filter",
                "verbose_name_plural": "Review filters",
                "ordering": ("name",),
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "default_manager_name": "objects",
            },
        ),
        migrations.RemoveIndex(
            model_name="crfpriority",
            name="edc_metadat_modifie_b47490_idx",
        ),
        migrations.RemoveIndex(
            model_name="crfpriority",
            name="edc_metadat_user_mo_4d959a_idx",
        ),
        migrations.RemoveIndex(
            model_name="crfpriority",
            name="edc_metadata_crfpriority_a0idx",
        ),
        migrations.RemoveConstraint(
            model_name="crfpriority",
            name="edc_metadata_crfpriority_model_schedule_uniq",
        ),
        migrations.DeleteModel(
            name="CrfPriority",
        ),
        migrations.AddField(
            model_name="reviewfilter",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="reviewfilter",
            index=models.Index(
                fields=["modified", "created"], name="edc_metadat_modifie_43446f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewfilter",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_metadat_user_mo_b3755f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewfilter",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="edc_metadata_reviewfilter_user_name_uniq"
            ),
        ),
    ]
