# Generated by Django 6.0.6 on 2026-06-25 23:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_metadata", "0041_reviewfilter_and_more"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CrfMetadataUnavailable",
            new_name="CrfMetadataMissing",
        ),
        migrations.RenameModel(
            old_name="DataUnavailableReason",
            new_name="DataMissingReason",
        ),
        migrations.RenameModel(
            old_name="HistoricalCrfMetadataUnavailable",
            new_name="HistoricalCrfMetadataMissing",
        ),
        migrations.RenameModel(
            old_name="HistoricalRequisitionMetadataUnavailable",
            new_name="HistoricalRequisitionMetadataMissing",
        ),
        migrations.RenameModel(
            old_name="RequisitionMetadataUnavailable",
            new_name="RequisitionMetadataMissing",
        ),
        migrations.RemoveConstraint(
            model_name="crfmetadatamissing",
            name="edc_metadata_crfmetadataunavailable_natkey_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="requisitionmetadatamissing",
            name="edc_metadata_requisitionmetadataunavailable_natkey_uniq",
        ),
        migrations.RenameIndex(
            model_name="crfmetadatamissing",
            new_name="edc_metadat_modifie_33fc0c_idx",
            old_name="edc_metadat_modifie_dfc340_idx",
        ),
        migrations.RenameIndex(
            model_name="crfmetadatamissing",
            new_name="edc_metadat_user_mo_9ae298_idx",
            old_name="edc_metadat_user_mo_bf9c50_idx",
        ),
        migrations.RenameIndex(
            model_name="crfmetadatamissing",
            new_name="edc_metadat_subject_1ba21b_idx",
            old_name="edc_metadat_subject_42e20a_idx",
        ),
        migrations.RenameIndex(
            model_name="datamissingreason",
            new_name="edc_metadat_display_11f34c_idx",
            old_name="edc_metadat_display_835d7e_idx",
        ),
        migrations.RenameIndex(
            model_name="requisitionmetadatamissing",
            new_name="edc_metadat_modifie_2dfffc_idx",
            old_name="edc_metadat_modifie_274cb3_idx",
        ),
        migrations.RenameIndex(
            model_name="requisitionmetadatamissing",
            new_name="edc_metadat_user_mo_162a34_idx",
            old_name="edc_metadat_user_mo_a5a2ee_idx",
        ),
        migrations.RenameIndex(
            model_name="requisitionmetadatamissing",
            new_name="edc_metadat_subject_60a1e8_idx",
            old_name="edc_metadat_subject_5bc90c_idx",
        ),
        migrations.AddConstraint(
            model_name="crfmetadatamissing",
            constraint=models.UniqueConstraint(
                fields=(
                    "subject_identifier",
                    "visit_schedule_name",
                    "schedule_name",
                    "visit_code",
                    "visit_code_sequence",
                    "model",
                ),
                name="edc_metadata_crfmetadatamissing_natkey_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="requisitionmetadatamissing",
            constraint=models.UniqueConstraint(
                fields=(
                    "subject_identifier",
                    "visit_schedule_name",
                    "schedule_name",
                    "visit_code",
                    "visit_code_sequence",
                    "model",
                    "panel_name",
                ),
                name="edc_metadata_requisitionmetadatamissing_natkey_uniq",
            ),
        ),
    ]
