# Generated by Django 6.0.6 on 2026-06-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "edc_metadata",
            "0042_rename_crfmetadataunavailable_crfmetadatamissing_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crfmetadatamissing",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "CRF flagged missing",
                "verbose_name_plural": "CRFs flagged missing",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalcrfmetadatamissing",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical CRF flagged missing",
                "verbose_name_plural": "historical CRFs flagged missing",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrequisitionmetadatamissing",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Requisition flagged missing",
                "verbose_name_plural": "historical Requisitions flagged missing",
            },
        ),
        migrations.AlterModelOptions(
            name="requisitionmetadatamissing",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Requisition flagged missing",
                "verbose_name_plural": "Requisitions flagged missing",
            },
        ),
    ]
