# Generated by Django 6.0.4 on 2026-05-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_visit_schedule", "0022_visitschedulesummary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitschedulesummary",
            name="label",
            field=models.CharField(max_length=255, unique=True, verbose_name="Label"),
        ),
    ]
