# Generated by Django 6.0.6 on 2026-06-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_auth", "0037_alter_edcpermissions_revision_alter_role_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="institution",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
