# Generated by Django 5.2.10 on 2026-04-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edc_appointment", "0052_alter_appointment_appt_timing_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointmenttype",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("display_index", "display_name"),
                "verbose_name": "Appointment Type",
                "verbose_name_plural": "Appointment Types",
            },
        ),
        migrations.AlterModelOptions(
            name="infosources",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("display_index", "display_name"),
                "verbose_name": "Information Source",
                "verbose_name_plural": "Information Sources",
            },
        ),
    ]
