# Generated by Django 5.2.11 on 2026-04-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_appointment", "0053_alter_appointmenttype_options_and_more"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=[
                    "subject_identifier",
                    "visit_schedule_name",
                    "schedule_name",
                    "visit_code",
                    "visit_code_sequence",
                    "site",
                ],
                name="edc_appoint_subject_b821e6_idx",
            ),
        ),
    ]
