# Generated by Django 6.0.8 on 2026-08-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edc_export", "0025_delete_exportreceipt_delete_filehistory_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="datarequest",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="datarequesthistory",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="datarequest",
            name="site",
        ),
        migrations.RemoveField(
            model_name="datarequesthistory",
            name="site",
        ),
        migrations.RemoveField(
            model_name="historicaldatarequest",
            name="site",
        ),
    ]
