from __future__ import annotations

from django.db import models
from django.utils import timezone

from edc_identifier.model_mixins import NonUniqueSubjectIdentifierFieldMixin
from edc_sites.model_mixins import SiteModelMixin
from edc_visit_schedule.model_mixins import (
    VisitCodeFieldsModelMixin,
    VisitScheduleFieldsModelMixin,
)


class ManageMissingModelMixin(
    NonUniqueSubjectIdentifierFieldMixin,
    SiteModelMixin,
    VisitScheduleFieldsModelMixin,
    VisitCodeFieldsModelMixin,
    models.Model,
):
    """Shared fields for the CRF/Requisition "data unavailable" flags.

    Keyed by the metadata natural key (subject_identifier, visit schedule,
    visit code and sequence, model) — never the CrfMetadata/RequisitionMetadata
    primary key, which is regenerated by ``update_metadata``.
    """

    model = models.CharField(
        max_length=50,
        help_text="Dotted model label, matches CrfMetadata/RequisitionMetadata.model.",
    )

    reason = models.ForeignKey(
        "edc_metadata.DataMissingReason",
        on_delete=models.PROTECT,
        related_name="+",
    )

    comment = models.TextField(default="", blank=True)

    decision_datetime = models.DateTimeField(default=timezone.now)

    class Meta:
        abstract = True
