ALLOCATED = "allocated"
ALREADY_CONFIRMED = "already_confirmed"
AVAILABLE = "available"
CANCELLED = "cancelled"
CENTRAL_LOCATION = "central"
CONTROL_ARM = "control_arm"
DAYS = "days"
DISPENSED = "dispensed"
FILLED = "filled"
INVALID = "invalid"
IN_PROGRESS_APPT = "in_progress"
NOT_STORED_AT_LOCATION = "not_stored_at_location"
PER_DAY = "day"
PER_HR = "hr"
PRESCRIPTION_ACTION = "prescription"
PRINT_SELECTED = "print_selected"
PROBLEM = "problem"
RECEIVE = "receive"
REPACK = "repack"
RESERVED = "reserved"
SINGLE = "single"
SOLUTION = "SOLUTION"
ZERO_ITEM = "zero_item"

# Stock transaction types
# Intake
TXN_RECEIVED = "RECEIVED"
# Transformation
TXN_REPACK_CONSUMED = "REPACK_CONSUMED"
TXN_REPACK_PRODUCED = "REPACK_PRODUCED"
# Subject binding
TXN_ALLOCATED = "ALLOCATED"
TXN_ALLOCATION_ENDED = "ALLOCATION_ENDED"
# Forward movement
TXN_TRANSFER_DISPATCHED = "TRANSFER_DISPATCHED"
TXN_TRANSFER_RECEIVED = "TRANSFER_RECEIVED"
TXN_STORED = "STORED"
TXN_BIN_MOVED = "BIN_MOVED"
TXN_DISPENSED = "DISPENSED"
# Reverse movement
TXN_RETURN_REQUESTED = "RETURN_REQUESTED"
TXN_RETURN_DISPATCHED = "RETURN_DISPATCHED"
TXN_RETURN_RECEIVED = "RETURN_RECEIVED"
TXN_RETURN_DISPOSITION_REPOOLED = "RETURN_DISPOSITION_REPOOLED"
TXN_RETURN_DISPOSITION_QUARANTINED = "RETURN_DISPOSITION_QUARANTINED"
TXN_RETURN_DISPOSITION_DESTROYED = "RETURN_DISPOSITION_DESTROYED"
# Exceptions
TXN_ADJUSTED = "ADJUSTED"
TXN_DAMAGED = "DAMAGED"
TXN_LOST = "LOST"
TXN_EXPIRED = "EXPIRED"
TXN_VOIDED = "VOIDED"
# Corrections (schema in V1, machinery in V2)
TXN_REVERSAL = "REVERSAL"

ALLOCATION_END_REASONS = frozenset(
    {
        "dispensed",
        "returned",
        "reallocated",
        "damaged",
        "expired",
        "voided",
        "lost",
    }
)
