from django.urls import path

from .admin_site import edc_pharmacy_admin
from .views import (
    AddToStorageBinView,
    AllocateToSubjectView,
    BulkStockReportView,
    CeleryTaskStatusView,
    ConfirmaAtLocationView,
    ConfirmStockFromQuerySetView,
    ContainerBalanceReportView,
    DispenseView,
    HomeView,
    LedgerView,
    MoveToStorageBinView,
    OrderEditView,
    OrderHomeView,
    OrderItemEditView,
    OrderView,
    PrepareAndReviewStockRequestView,
    PrintLabelsView,
    ReceiveHomeView,
    ReceiveLotAddView,
    ReceiveOrderEditView,
    ReceiveOrderItemView,
    ReceiveOrderView,
    ReceiveSupplierAddView,
    ReceiveSupplierEditView,
    RepackEditView,
    RepackHomeView,
    RepackView,
    ReturnCentralView,
    ReturnDispositionView,
    ReturnReceiveView,
    ReturnRequestView,
    SiteStockReportView,
    StockAdjustmentView,
    StockRequestEditView,
    StockRequestHomeView,
    StockRequestView,
    StockTakeHomeView,
    StockTakeResultsView,
    StockTakeScanView,
    StockTransferEditView,
    StockTransferHomeView,
    TransferStockView,
    get_stock_transfers_view,
    print_order_view,
    print_return_manifest_view,
    print_stock_transfer_manifest_view,
    print_stock_view,
)

app_name = "edc_pharmacy"


urlpatterns = [
    path(
        "dispense/<int:location_id>/<uuid:formulation_id>/"
        "<str:subject_identifier>/<int:container_count>/",
        DispenseView.as_view(),
        name="dispense_url",
    ),
    path("get-stock-transfers/", get_stock_transfers_view, name="get_stock_transfers_url"),
    path(
        "confirm-at-location/<uuid:session_uuid>/<str:stock_transfer_identifier>/"
        "<int:location_id>/<int:items_to_scan>/",
        ConfirmaAtLocationView.as_view(),
        name="confirm_at_location_url",
    ),
    path(
        "confirm-at-location/<str:stock_transfer_identifier>/"
        "<int:location_id>/<int:items_to_scan>/",
        ConfirmaAtLocationView.as_view(),
        name="confirm_at_location_url",
    ),
    path(
        "confirm-at-location/<int:location_id>/<int:items_to_scan>/",
        ConfirmaAtLocationView.as_view(),
        name="confirm_at_location_url",
    ),
    path(
        "confirm-at-location/<int:site_id>/",
        ConfirmaAtLocationView.as_view(),
        name="confirm_at_location_url",
    ),
    path(
        "confirm-at-location/<str:location_name>/",
        ConfirmaAtLocationView.as_view(),
        name="confirm_at_location_url",
    ),
    path(
        "review-stock-request/<uuid:stock_request>/<uuid:session_uuid>/",
        PrepareAndReviewStockRequestView.as_view(),
        name="review_stock_request_url",
    ),
    path(
        "allocate/<uuid:stock_request>/<uuid:assignment>/",
        AllocateToSubjectView.as_view(),
        name="allocate_url",
    ),
    path(
        "allocate/<uuid:stock_request>/<uuid:assignment>",
        AllocateToSubjectView.as_view(),
        name="allocate_url",
    ),
    path(
        "confirm-stock-qs/<uuid:session_uuid>/",
        ConfirmStockFromQuerySetView.as_view(),
        name="confirm_stock_from_queryset_url",
    ),
    path(
        "allocate/<uuid:stock_request>/",
        AllocateToSubjectView.as_view(),
        name="allocate_url",
    ),
    path(
        "stock-transfer/",
        StockTransferHomeView.as_view(),
        name="stock_transfer_home_url",
    ),
    path(
        "stock-transfer/add/",
        StockTransferEditView.as_view(),
        name="stock_transfer_add_url",
    ),
    path(
        "transfer-stock/<uuid:stock_transfer>/",
        TransferStockView.as_view(),
        name="transfer_stock_url",
    ),
    path(
        "review-stock-request/<uuid:stock_request>/",
        PrepareAndReviewStockRequestView.as_view(),
        name="review_stock_request_url",
    ),
    path(
        "print-labels/<str:model>/<uuid:session_uuid>/<str:label_configuration>",
        PrintLabelsView.as_view(),
        name="print_labels_url",
    ),
    path(
        "print-labels/<str:model>/<uuid:session_uuid>/",
        PrintLabelsView.as_view(),
        name="print_labels_url",
    ),
    path(
        "manifest/<uuid:stock_transfer>/",
        print_stock_transfer_manifest_view,
        name="generate_manifest",
    ),
    path(
        "return-manifest/<uuid:return_request>/",
        print_return_manifest_view,
        name="return_manifest_url",
    ),
    path("stock_report/<uuid:session_uuid>/", print_stock_view, name="stock_report"),
    path(
        "add-to-storage-bin/<uuid:storage_bin>/<int:items_to_scan>/",
        AddToStorageBinView.as_view(),
        name="add_to_storage_bin_url",
    ),
    path(
        "add-to-storage-bin/<uuid:storage_bin>/",
        AddToStorageBinView.as_view(),
        name="add_to_storage_bin_url",
    ),
    path(
        "move-to-storage-bin/<uuid:storage_bin>/<int:items_to_scan>/",
        MoveToStorageBinView.as_view(),
        name="move_to_storage_bin_url",
    ),
    path(
        "move-to-storage-bin/<uuid:storage_bin>/",
        MoveToStorageBinView.as_view(),
        name="move_to_storage_bin_url",
    ),
    path(
        "task-status/<uuid:task_id>/",
        CeleryTaskStatusView.as_view(),
        name="celery_task_status_url",
    ),
    path(
        "stock-transfer-confirmation/",
        ConfirmaAtLocationView.as_view(),
        name="confirm_at_location_url",
    ),
    path(
        "dispense/",
        DispenseView.as_view(),
        name="dispense_url",
    ),
    # ── Order management workflow ──────────────────────────────────────────
    path(
        "order/",
        OrderHomeView.as_view(),
        name="order_home_url",
    ),
    path(
        "order/add/",
        OrderEditView.as_view(),
        name="order_add_url",
    ),
    path(
        "order/<uuid:order>/",
        OrderView.as_view(),
        name="order_url",
    ),
    path(
        "order/<uuid:order>/edit/",
        OrderEditView.as_view(),
        name="order_edit_url",
    ),
    path(
        "order/<uuid:order>/items/add/",
        OrderItemEditView.as_view(),
        name="order_item_add_url",
    ),
    path(
        "order/<uuid:order>/items/<uuid:order_item>/",
        OrderItemEditView.as_view(),
        name="order_item_edit_url",
    ),
    path(
        "order/<uuid:order>/print/",
        print_order_view,
        name="print_order_url",
    ),
    # ── Receive workflow ───────────────────────────────────────────────────
    path(
        "receive/",
        ReceiveHomeView.as_view(),
        name="receive_home_url",
    ),
    path(
        "receive/<uuid:order>/",
        ReceiveOrderView.as_view(),
        name="receive_order_url",
    ),
    path(
        "receive/<uuid:order>/edit/",
        ReceiveOrderEditView.as_view(),
        name="receive_order_edit_url",
    ),
    path(
        "receive/<uuid:order>/<uuid:order_item>/",
        ReceiveOrderItemView.as_view(),
        name="receive_order_item_url",
    ),
    path(
        "receive/<uuid:order>/<uuid:order_item>/<uuid:receive_item>/edit/",
        ReceiveOrderItemView.as_view(),
        name="receive_item_edit_url",
    ),
    path(
        "receive/supplier/add/",
        ReceiveSupplierAddView.as_view(),
        name="receive_supplier_add_url",
    ),
    path(
        "receive/lot/<uuid:order_item>/add/",
        ReceiveLotAddView.as_view(),
        name="receive_lot_add_url",
    ),
    path(
        "receive/supplier/<uuid:pk>/edit/",
        ReceiveSupplierEditView.as_view(),
        name="receive_supplier_edit_url",
    ),
    # ── Stock request / allocation workflow ───────────────────────────────
    path(
        "stock-request/",
        StockRequestHomeView.as_view(),
        name="stock_request_home_url",
    ),
    path(
        "stock-request/add/",
        StockRequestEditView.as_view(),
        name="stock_request_add_url",
    ),
    path(
        "stock-request/<uuid:stock_request>/",
        StockRequestView.as_view(),
        name="stock_request_url",
    ),
    path(
        "stock-request/<uuid:stock_request>/edit/",
        StockRequestEditView.as_view(),
        name="stock_request_edit_url",
    ),
    # ── Repack workflow ────────────────────────────────────────────────────
    path(
        "repack/",
        RepackHomeView.as_view(),
        name="repack_home_url",
    ),
    path(
        "repack/add/",
        RepackEditView.as_view(),
        name="repack_add_url",
    ),
    path(
        "repack/<uuid:repack_request>/",
        RepackView.as_view(),
        name="repack_url",
    ),
    path(
        "repack/<uuid:repack_request>/edit/",
        RepackEditView.as_view(),
        name="repack_edit_url",
    ),
    # ── Return workflow ────────────────────────────────────────────────────
    path(
        "return-request/<uuid:return_request>/",
        ReturnRequestView.as_view(),
        name="return_request_url",
    ),
    path(
        "return-request/",
        ReturnRequestView.as_view(),
        name="return_request_url",
    ),
    path(
        "return-central/",
        ReturnCentralView.as_view(),
        name="return_central_url",
    ),
    path(
        "stock-adjustments/",
        StockAdjustmentView.as_view(),
        name="stock_adjustments_url",
    ),
    path(
        "ledger/",
        LedgerView.as_view(),
        name="ledger_url",
    ),
    path(
        "return-receive/<uuid:return_request>/",
        ReturnReceiveView.as_view(),
        name="return_receive_url",
    ),
    path(
        "return-receive/",
        ReturnReceiveView.as_view(),
        name="return_receive_url",
    ),
    path(
        "return-disposition/<uuid:return_request>/",
        ReturnDispositionView.as_view(),
        name="return_disposition_url",
    ),
    path(
        "return-disposition/",
        ReturnDispositionView.as_view(),
        name="return_disposition_url",
    ),
    path(
        "bulk-stock-report/",
        BulkStockReportView.as_view(),
        name="bulk_stock_report_url",
    ),
    path(
        "container-balance-report/",
        ContainerBalanceReportView.as_view(),
        name="container_balance_report_url",
    ),
    path(
        "site-stock-report/",
        SiteStockReportView.as_view(),
        name="site_stock_report_url",
    ),
    path(
        "stock-take/",
        StockTakeHomeView.as_view(),
        name="stock_take_home_url",
    ),
    path(
        "stock-take/<uuid:storage_bin>/",
        StockTakeScanView.as_view(),
        name="stock_take_scan_url",
    ),
    path(
        "stock-take/results/<uuid:stock_take>/",
        StockTakeResultsView.as_view(),
        name="stock_take_results_url",
    ),
    # ───────────────────────────────────────────────────────────────────────
    path("admin/", edc_pharmacy_admin.urls),
    # path("admin/history/", edc_pharmacy_history_admin.urls),
    path("", HomeView.as_view(), name="home_url"),
]
