# Generated by Django 5.2.10 on 2026-04-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edc_facility", "0018_alter_healthfacility_revision_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="healthfacilitytypes",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "ordering": ("display_index", "display_name"),
                "verbose_name": "Health Facility Type",
                "verbose_name_plural": "Health Facility Types",
            },
        ),
    ]
